---
- name: Install rabbitmq
  homebrew: name=rabbitmq state=latest
  notify: Restart rabbitmq

- name: Set rabbitmq config
  template: src=rabbitmq.config.j2 dest=/usr/local/etc/rabbitmq/rabbitmq.config
  notify: Restart rabbitmq

- name: Is the http management plugin enabled?
  command: /usr/local/sbin/rabbitmq-plugins list
  register: rabbitmq_enabled_plugins
  changed_when: false

- name: Enable http management interface
  command: /usr/local/sbin/rabbitmq-plugins enable rabbitmq_management
  notify: Restart rabbitmq
  when: rabbitmq_enabled_plugins.stdout.find('[E*] rabbitmq_management') == -1
