---
- name: Add homebrew tap
  homebrew_tap: name=homebrew/apache state=present

- name: Install apache
  homebrew: name=homebrew/apache/httpd24 state=latest update_homebrew=yes install_options=with-privileged-ports
  notify: Restart apache

- name: Create config directory
  file: path=/Users/{{ ansible_user }}/.env/config state=directory

- name: Create logs directory
  file: path=/Users/{{ ansible_user }}/.env/logs state=directory

- name: Enable SSL module
  replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="^#LoadModule ssl_module" replace="LoadModule ssl_module"
  notify: Restart apache

- name: Check for ssl certificate existance
  stat: path=/Users/{{ ansible_user }}/.env/config/server.crt
  register: ssl_certificate_exists

- name: Generate SSL certficate and key
  command: openssl req -new -newkey rsa:2048 -x509 -nodes -days 365 -subj "/C=US/ST=Rhode Island/L=Quahog/O=Development/OU=Local/CN=*.dev" -keyout /Users/{{ ansible_user }}/.env/config/server.key -out /Users/{{ ansible_user }}/.env/config/server.crt
  when: ssl_certificate_exists.stat.exists == false

- name: Enable rewrite module
  replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="^#LoadModule rewrite_module" replace="LoadModule rewrite_module"
  notify: Restart apache

- name: Enable vhost_alias module
  replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="^#LoadModule vhost_alias_module" replace="LoadModule vhost_alias_module"
  notify: Restart apache

- name: Include virtual host config
  replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="^#Include /usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf" replace="Include /usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf"
  notify: Restart apache

- name: Enable proxy_module
  replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="^#LoadModule proxy_module" replace="LoadModule proxy_module"
  notify: Restart apache

- name: Enable fcgi_module
  replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="^#LoadModule proxy_fcgi_module" replace="LoadModule proxy_fcgi_module"
  notify: Restart apache

- name: Add host config
  template: src=virtual_hosts.conf dest=/usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf
  notify: Restart apache

- name: Start apache at login
  copy: src=/usr/local/opt/httpd24/homebrew.mxcl.httpd24.plist dest=/Library/LaunchDaemons/homebrew.mxcl.httpd24.plist owner=root group=wheel mode=0644
  become: true
  become_user: "root"

- name: Create sites directory
  file: path=/Users/{{ ansible_user }}/Sites state=directory
