---
- name: Install mysql
  homebrew: name=mysql state=latest
  notify: Restart mysql

- name: Set utc timezone
  blockinfile:
    dest: /usr/local/etc/my.cnf
    block: |
      [mysqld]
      default_time_zone=+0:00
  notify: Restart mysql
